name: "Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test action

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Run build
        run: npm run build

      - name: Ensure no pending Git changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "There are pending Git changes after running the build. Did you forget to commit the .js files?"
            exit 1
          fi

      - name: Run tests
        run: npm run test

      - name: Load test key
        id: get_key
        run: |
          value=$(cat __tests__/test_key_b64.txt)
          echo "text=$value" >> $GITHUB_OUTPUT

      - uses: ./
        name: zipalign and Sign APK
        with:
          releaseDirectory: __tests__/apk-zip
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android
          zipAlign: true

      - uses: ./
        name: Sign APK
        with:
          releaseDirectory: __tests__/apk
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android

      - uses: ./
        name: Sign AAB
        with:
          releaseDirectory: __tests__/aab
          signingKeyBase64: ${{ steps.get_key.outputs.text }}
          alias: test_key
          keyStorePassword: android
          keyPassword: android
